### ISSUE TITLE
Infinite Copper

### ISSUE THREAD

**Issue by Darkxx130x** [EnigmaticaModpacks/Enigmatica8#299] opened 2022-10-02 14:16 UTC
### Modpack Version

2.3.0

### Describe your issue.

Putting a block of copper into a stone cutter can turn it into four cut copper blocks. but if you put one cut copper block into a stone cutter you get 4 blocks of copper so you can repeat the process to get infinite copper. Not a game breaking bug but i figured you guys might not want it in the pack

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

CornPop#4846

**Comment by Kanzaji** [comment] 2022-10-02 15:10
Duplicate of #283, Already fixed on latest version 😋

**Closed** 2022-10-02 15:11 UTC
Labels: Bug
