### ISSUE TITLE
Gregtech Intergalactical

### ISSUE THREAD

**Issue by Leclowndu93150** [EnigmaticaModpacks/Enigmatica8#279] opened 2022-09-19 16:18 UTC
### URL

https://www.curseforge.com/minecraft/mc-mods/gregtech-intergalactical

### Why would you like the mod added?

Gr🥚

**Comment by Kanzaji** [comment] 2022-09-19 16:20
Duplicate of #277.

**Comment by Leclowndu93150** [comment] 2022-09-19 16:24
> Duplicate of #277.

i know

**Closed as not planned** 2022-09-19 16:29 UTC
Labels: Status: Won't Fix, Suggestion

**Comment by Gcat101** [comment] 2022-09-19 16:39
NO STOP DON'T SPAM THIS WAS JUST A LITTLE TROLLING DO NOT SPAM OK
