### ISSUE TITLE
OpenBlocks Elevator

### ISSUE THREAD

**Issue by NickyMB** [EnigmaticaModpacks/Enigmatica8#239] opened 2022-08-28 08:38 UTC
### URL

https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator

### Why would you like the mod added?

It will help in fast travel between levels in high bases

**Comment by Kanzaji** [comment] 2022-08-28 09:09
Duplicate of #181

**Closed** 2022-08-28 09:44 UTC
Labels: Status: Won't Fix, Suggestion
