### ISSUE TITLE
Mob Grinding Utils

### ISSUE THREAD

**Issue by panzeson** [EnigmaticaModpacks/Enigmatica8#77] opened 2022-02-20 10:07 UTC
### URL

https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils

### Why would you like the mod added?

Just throwing this out there, saw that there was a 1.18 version of this mod. This would be a really nice addition, especially with apotheosis in the modpack now.

**Comment by NillerMedDild** [comment] 2022-02-20 12:08
Duplicate of #54

**Closed by NillerMedDild** 2022-02-20 12:08 UTC
Labels: Suggestion
